FROM  quay.io/redhat_emp1/uksummit-rhelbase

# We make four distinct layers so if there are application changes the library layers can be re-used
RUN mkdir -p /store-display /store-display/lib /store-display/app /store-display/quarkus 
COPY ./store-display/target/quarkus-app/lib/ /store-display/lib/
COPY ./store-display/target/quarkus-app/*.jar /store-display/
COPY ./store-display/target/quarkus-app/app/ /store-display/app/
COPY ./store-display/target/quarkus-app/quarkus/ /store-display/quarkus/
COPY ./store-display.service /etc/systemd/system

# We make four distinct layers so if there are application changes the library layers can be re-used
RUN mkdir -p /store-camera /store-camera/lib /store-camera/app /store-camera/quarkus 
COPY ./store-camera/target/quarkus-app/lib/ /store-camera/lib/
COPY ./store-camera/target/quarkus-app/*.jar /store-camera/
COPY ./store-camera/target/quarkus-app/app/ /store-camera/app/
COPY ./store-camera/target/quarkus-app/quarkus/ /store-camera/quarkus/
COPY ./store-camera.service /etc/systemd/system

# Start the store display service
RUN systemctl enable store-display.service
RUN systemctl enable store-camera.service
