FROM registry.redhat.io/rhel9/rhel-bootc:9.4

# COPY the auth.json to enable the image to authenticate with Quay
COPY ./auth.json /etc/ostree/

#add a user
RUN useradd redhat -p redhat 
RUN echo redhat | passwd redhat --stdin
RUN usermod -aG wheel redhat 

#install java and graphical UI 
RUN yum group install -y GNOME base-x Fonts && dnf clean all
RUN systemctl set-default graphical.target
RUN yum install -y java-21-openjdk firefox && dnf clean all
RUN yum install -y python39 && dnf clean all

# We make four distinct layers so if there are application changes the library layers can be re-used
RUN mkdir -p /store-display /store-display/lib /store-display/app /store-display/quarkus 
COPY ./store-display/target/quarkus-app/lib/ /store-display/lib/
COPY ./store-display/target/quarkus-app/*.jar /store-display/
COPY ./store-display/target/quarkus-app/app/ /store-display/app/
COPY ./store-display/target/quarkus-app/quarkus/ /store-display/quarkus/
COPY ./store-display.service /etc/systemd/system

# We make four distinct layers so if there are application changes the library layers can be re-used
RUN mkdir -p /store-camera /store-camera/lib /store-camera/app /store-camera/quarkus 
COPY ./store-camera/target/quarkus-app/lib/ /store-camera/lib/
COPY ./store-camera/target/quarkus-app/*.jar /store-camera/
COPY ./store-camera/target/quarkus-app/app/ /store-camera/app/
COPY ./store-camera/target/quarkus-app/quarkus/ /store-camera/quarkus/
COPY ./store-camera.service /etc/systemd/system

# Start the store display service
RUN systemctl enable store-display.service
RUN systemctl enable store-camera.service